config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users
  root 'profiles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(params.required(:profile).permit(:name, :age))
    if @profile.save
    redirect_to profiles_path
  else
    render new
  end
end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(params.required(:profile).permit(:name, :age))
      redirect_to profiles_path
    else
      render new
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    if @profile.delete
    redirect_to profiles_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nxp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
     <div class="container" >
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
   </body>
  </div> 
</html>

app/views/profiles/_form.html.erb
<%= form_for profile do |form| %>

  <div class="field form-group">
    <%= form.text_field :name, class: "form-control", placeholder: "name", required: "true" %>
  </div>
  <div class="field form-group">
    <%= form.text_field :age, class: "form-control", placeholder: "age", required: "true" %>


    <div class="actions">
    <%= form.submit class: "btn btn-secondary"%>
    </div><br/>
<% end %>

app/views/profiles/edit.html.erb
<h1> Edit </h1>
<%= render 'form', profile: @profile %>

<%= link_to 'back', profiles_path,class:"btn btn-primary" %>

app/views/profiles/index.html.erb
<h1> Hi LJ </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th> Name </th>
      <th> Age </th>
      <th> </th>
      <th> Action </th>
    </tr>
  </thead>

  <tbody>
  <% @profiles.each do |profile| %>
    <tr>
    <td> <%= profile.name %></td>
    <td> <%= profile.age %></td>
    <td> <%= link_to 'show', profile_path(profile) %></td>
    <td> <%= link_to 'update', edit_profile_path(profile) %></td>
    <td> <%= link_to 'delete', profile_path(profile), method: :delete, data:{confirm: "Ok" } %></td>
    </tr>
  </tbody>
<% end %>
</table>
</br>
<%= link_to "Add", new_profile_path, class:"btn btn-primary" %>
</br>
</br>
<%= link_to "Logout", destroy_user_session_path, class:"btn btn-primary", method: :delete %>

app/views/profiles/new.html.erb
<h1> Form </h1>

<%= render "form",  profile: @profile %>

<%= link_to 'Back', profiles_path, class:"btn btn-primary" %>

app/views/profiles/show.html.erb
<h1> Show </h1>

<table class="table table-striped">
      <th> Name </th>
      <th> Age </th>
  <tr>
    <td><%= @profile.name %></td>
    <td><%= @profile.age %></td>
  </tr>
</table>
</br>
<%= link_to 'Back', profiles_path, class:"btn btn-primary" %>